class Nwmls::VacantLandListing < Nwmls::Listing
  CODES = HashWithIndifferentAccess.new(
    LN: 'Listing Number',
    PTYP: 'Property Type',
    LAG: 'Listing Agent Number',
    ST: 'Status',
    LP: 'Listing Price',
    LPH: 'Listing Price History',
    SP: 'Selling Price',
    OLP: 'Original Price',
    HSN: 'House Number',
    DRP: 'Directional Prefix',
    STR: 'Street',
    SSUF: 'Street Suffix',
    DRS: 'Directional Suffix',
    UNT: 'Unit',
    CIT: 'City',
    STA: 'State',
    ZIP: 'Zip Code',
    PL4: 'Zip Plus 4',
    LSF: 'Lot Square Footage',
    UD: 'Update Date',
    AR: 'Area',
    DSRNUM: 'Community Number',
    LDR: 'List Date Received',
    LD: 'List Date',
    CLO: 'Selling Date',
    LO: 'Listing Office Number',
    TAX: 'Parcel Number',
    MAP: 'Map Page',
    GRDX: 'X Coordinate',
    GRDY: 'Y Coordinate',
    SAG: 'Selling Agent Number',
    SO: 'Selling Office Number',
    NIA: 'Publish To Internet',
    MR: 'Marketing Remarks',
    LONG: 'Longitude',
    LAT: 'Latitude',
    PDR: 'Pending Date',
    CLA: 'Co-Listing Agent Number',
    SHOADR: 'Show Address to Public',
    DD: 'Directions',
    AVDT: 'Available Date',
    INDT: 'Inactive Date',
    COU: 'County',
    CDOM: 'Cumulative Days on Market',
    CTDT: 'Contingent Date',
    DOM: 'Days On Market',
    SCA: 'Selling Co Agent Number',
    SCO: 'Selling Co Office Number',
    VIRT: 'Virtual Tour URL',
    SD: 'School District',
    SDT: 'Status Date',
    FIN: 'Financing',
    MAPBOOK: 'Map Book',
    DSR: 'Community Name',
    FBT: 'Full Bathrooms',
    TQBT: 'Three Quarter Bathrooms',
    HBT: 'Half Bathrooms',
    QBT: 'Quarter Bathrooms',
    SFS: 'Square Footage Source',
    LSZS: 'Lot Size Source',
    HSNA: 'Street Number Modifier',
    COLO: 'Co Office',
    PIC: 'Picture Count',
    BLK: 'Block',
    EL: 'Elementary School',
    ELE: 'Electricity',
    ESM: 'Easements',
    F17: 'Form 17',
    GAS: 'Gas Available',
    JH: 'Junior High',
    LSZ: 'Lot Dimensions',
    LT: 'Lot Number',
    LVL: 'Level',
    PRJ: 'Project',
    PTO: 'Preliminary Title Ordered',
    QTR: 'Three Quarter Baths Total',
    RD: 'Road On Which Side of Property',
    SAP: 'Approved Number of Bedrooms',
    SDA: 'Septic Designed and Applied for',
    SEC: 'Section/Township/Range',
    SEP: 'Septic System Installed',
    SFA: 'Soils Feasibility Available',
    SH: 'Senior High',
    SLP: 'Slope of Property',
    SML: 'Show Map Link to Public',
    SNR: 'Senior Exemption',
    SST: 'Septic System Type',
    STY: 'Style',
    SUR: 'Survey Information',
    SWR: 'Sewer',
    TER: 'Terms Remarks',
    TX: 'Tax Amount',
    TXY: 'Tax Year',
    WFG: 'Waterfront Footage',
    WRJ: 'Water Jurisdiction',
    ZJD: 'Zoning Jurisdiction',
    ZNR: 'Zoning Remarks',
    ATF: 'Assessment Fees',
    DOC: 'Documents Provided',
    FTR: 'Property Features',
    GZC: 'General Zoning Classification',
    IMP: 'Improvements',
    LDE: 'Lot Details',
    POS: 'Possession',
    RDI: 'Road Information',
    RS2: 'Restrictions',
    TPO: 'Topography',
    TRM: 'Terms',
    VEW: 'View',
    WFT: 'Waterfront',
    WTR: 'Water',
    CMFE: 'Community Features',
    PARQ: 'Third Party Required',
    BREO: 'Bank Owned',
    AllowAVM: 'Allow AVM',
    ProhibitBlogging: 'Allow Blog',
  )
  acts_as_nwmls_listing :property_type => 'VACL', :attribute_mappings => CODES
end
